//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by RainlendarDLL.rc
//
#define IDD_BACKGROUND                  102
#define IDD_WEEKNUMBERS                 103
#define IDD_GENERAL                     106
#define IDD_DAYS                        107
#define IDD_WEEKDAYS                    108
#define IDD_TODAY                       109
#define IDD_MONTH                       110
#define IDD_YEAR                        111
#define IDD_EVENT                       112
#define IDR_MENU1                       1000
#define IDC_X                           1000
#define IDC_Y                           1001
#define IDC_DAYS_Y                      1001
#define IDC_START_FROM_MONDAY           1002
#define IDC_DAYS_W                      1002
#define IDC_START_DELAY                 1003
#define IDC_DAYS_H                      1003
#define IDC_BACKGROUND_BROWSE           1004
#define IDC_BACKGROUND                  1005
#define IDC_DAYS_RASTERIZER             1006
#define IDC_START_HIDDEN                1006
#define IDC_DAYS_ENABLE                 1007
#define IDC_DISABLE_HOTKEYS             1007
#define IDC_USE_WINDOW_NAME             1008
#define IDC_DAYS_SELECT                 1009
#define IDC_DAYS_FONTNAME               1010
#define IDD_EDITEVENT                   1010
#define IDC_DAYS_BROWSE                 1011
#define IDD_SERVER                      1011
#define IDC_DAYS_COMPONENTS_10          1012
#define IDD_PROPPAGE_MEDIUM             1012
#define IDD_PROPPAGE_SMALL              1012
#define IDC_DAYS_COMPONENTS_32          1013
#define IDC_DAYS_ALIGN                  1014
#define IDC_DAYS_IGNORE_TODAY           1015
#define IDC_TODAY_ENABLE                1015
#define IDC_DAYS_BITMAP                 1016
#define IDC_DAYS_X                      1017
#define IDC_WEEKDAYS_ENABLE             1018
#define IDC_DAYS_FONTCOLOR              1018
#define IDC_WEEKDAYS_RASTERIZER         1019
#define IDC_DAYS_IGNORE_EVENT           1019
#define IDC_WEEKDAYS_ALIGN              1020
#define IDC_WEEKDAYS_BITMAP             1023
#define IDC_WEEKDAYS_BROWSE             1024
#define IDC_WEEKDAYS_FONTCOLOR          1025
#define IDC_TODAY_COMPONENTS_1          1025
#define IDC_TODAY_COMPONENTS_10         1026
#define IDC_TODAY_COMPONENTS_32         1027
#define IDC_TODAY_BITMAP                1028
#define IDC_TODAY_BROWSE                1029
#define IDC_TODAY_RASTERIZER            1032
#define IDC_TODAY_ALIGN                 1033
#define IDC_MONTH_ENABLE                1034
#define IDC_MONTH_X                     1035
#define IDC_MONTH_Y                     1036
#define IDC_MONTH_RASTERIZER            1037
#define IDC_MONTH_ALIGN                 1038
#define IDC_MONTH_BROWSE                1041
#define IDC_MONTH_BITMAP                1042
#define IDC_YEAR_ENABLE                 1043
#define IDC_YEAR_X                      1044
#define IDC_YEAR_Y                      1045
#define IDC_YEAR_RASTERIZER             1046
#define IDC_YEAR_ALIGN                  1048
#define IDC_YEAR_BROWSE                 1050
#define IDC_YEAR_BITMAP                 1051
#define IDC_WEEKDAYS_FONTNAME           1052
#define IDC_WEEKDAYS_SELECT             1053
#define IDC_MONTH_FONTNAME              1054
#define IDC_MONTH_SELECT                1055
#define IDC_MONTH_FONTCOLOR             1056
#define IDC_TODAY_FONTNAME              1057
#define IDC_TODAY_SELECT                1058
#define IDC_TODAY_FONTCOLOR             1059
#define IDC_YEAR_FONTNAME               1060
#define IDC_YEAR_SELECT                 1061
#define IDC_YEAR_FONTCOLOR              1062
#define IDC_EVENT_ENABLE                1063
#define IDC_EVENT_RASTERIZER            1064
#define IDC_EVENT_ALIGN                 1065
#define IDC_EVENT_FONTNAME              1066
#define IDC_EVENT_SELECT                1067
#define IDC_EVENT_FONTCOLOR             1068
#define IDC_EVENT_BITMAP                1069
#define IDC_EVENT_BROWSE                1070
#define IDC_EVENT_COMPONENTS_1          1071
#define IDC_EVENT_COMPONENTS_10         1072
#define IDC_EVENT_COMPONENTS_32         1073
#define IDC_EVENT_TOOLTIP               1074
#define IDC_EVENT_MESSAGEBOX            1075
#define IDC_EVENT_EXECUTE               1076
#define IDC_EDITEVENT_MESSAGE           1077
#define IDC_WEEKNUM_ENABLE              1078
#define IDC_WEEKNUM_RASTERIZER          1079
#define IDC_WEEKNUM_ALIGN               1080
#define IDC_WEEKNUM_FONTNAME            1081
#define IDC_WEEKNUM_SELECT              1082
#define IDC_WEEKNUM_FONTCOLOR           1083
#define IDC_WEEKNUM_BITMAP              1084
#define IDC_WEEKNUM_BROWSE              1085
#define IDC_WEEKNUM_COMPONENTS_10       1086
#define IDC_WEEKNUM_COMPONENTS_54       1087
#define IDC_EVENT_CALENDAR              1088
#define IDC_EVENT_FONTCOLOR2            1089
#define IDC_EVENT_SELECT2               1090
#define IDC_EVENT_FONTNAME2             1091
#define IDC_EDITEVENT_BROWSE            1092
#define IDC_EDITEVENT_BITMAP            1093
#define IDC_EDITEVENT_LABEL             1094
#define IDC_EDITEVENT_FONTCOLOR         1095
#define IDC_SERVER_ENABLE               1096
#define IDC_SERVER_ADDRESS              1097
#define IDC_SERVER_PORT                 1098
#define IDC_SERVER_ID                   1099
#define IDC_SERVER_FREQUENCY            1101
#define IDC_SERVER_SYNC                 1104
#define IDC_SERVER_STATUS               1107
#define IDC_SERVER_STARTUP              1108
#define IDC_POLL_WALLPAPER              1110
#define IDC_BACKGROUND_TILE             1111
#define IDC_BACKGROUND_STRETCH          1112
#define IDC_BACKGROUND_COPYWALLPAPER    1113
#define IDC_WINDOW_MOVABLE              1114
#define IDC_WINDOW_ONBOTTOM             1115
#define IDC_WINDOW_NORMAL               1116
#define IDC_DAY                         1116
#define IDC_WINDOW_ONTOP                1117
#define IDC_WINDOW_MOUSEHIDE            1118
#define IDC_DAYS_SEPARATION             1132
#define IDC_DAYS_BITMAP_FRAME           1135
#define IDC_DAYS_FONT_FRAME             1136
#define IDC_DAYS_BITMAP_STATIC          1140
#define IDC_DAYS_COMPONENTS_STATIC      1141
#define IDC_DAYS_SEPARATION_STATIC      1142
#define IDC_DAYS_FONTCOLOR_STATIC       1143
#define IDC_DAYS_FONT_STATIC            1144
#define IDC_BACKGROUND_FILENAME         1149
#define IDC_TODAY_BITMAP_FRAME          1150
#define IDC_TODAY_FONT_FRAME            1151
#define IDC_TODAY_SEPARATION            1152
#define IDC_TODAY_SEPARATION_STATIC     1153
#define IDC_TODAY_COMPONENTS_STATIC     1154
#define IDC_TODAY_BITMAP_STATIC         1155
#define IDC_TODAY_FONT_STATIC           1156
#define IDC_TODAY_FONTCOLOR_STATIC      1157
#define IDC_EVENT_SEPARATION            1158
#define IDC_EVENT_BITMAP_STATIC         1159
#define IDC_EVENT_COMPONENTS_STATIC     1160
#define IDC_EVENT_SEPARATION_STATIC     1161
#define IDC_EVENT_BITMAP_FRAME          1162
#define IDC_EVENT_FONT_FRAME            1163
#define IDC_EVENT_FONTCOLOR_STATIC      1164
#define IDC_EVENT_FONT_STATIC           1165
#define IDC_WEEKDAYS_BITMAP_FRAME       1167
#define IDC_WEEKDAYS_BITMAP_STATIC      1168
#define IDC_WEEKDAYS_FONTCOLOR_STATIC   1169
#define IDC_WEEKDAYS_FONT_STATIC        1170
#define IDC_WEEKDAYS_FONT_FRAME         1171
#define IDC_WEEKNUM_COMPONENTS_32       1172
#define IDC_WEEKNUM_SEPARATION          1173
#define IDC_WEEKNUM_SEPARATION_STATIC   1174
#define IDC_WEEKNUM_BITMAP_FRAME        1175
#define IDC_WEEKNUM_BITMAP_STATIC       1176
#define IDC_WEEKNUM_FONTCOLOR_STATIC    1177
#define IDC_WEEKNUM_FONT_STATIC         1178
#define IDC_WEEKNUM_FONT_FRAME          1179
#define IDC_WEEKNUM_COMPONENTS_STATIC   1180
#define IDC_MONTH_FONTCOLOR_STATIC      1181
#define IDC_MONTH_BITMAP_STATIC         1182
#define IDC_MONTH_BITMAP_FRAME          1183
#define IDC_MONTH_FONT_FRAME            1184
#define IDC_MONTH_FONT_STATIC           1185
#define IDC_YEAR_SEPARATION             1186
#define IDC_YEAR_SEPARATION_STATIC      1187
#define IDC_YEAR_BITMAP_STATIC          1188
#define IDC_YEAR_BITMAP_FRAME           1189
#define IDC_YEAR_FONT_FRAME             1190
#define IDC_YEAR_FONTCOLOR_STATIC       1191
#define IDC_YEAR_FONT_STATIC            1192
#define ID_SKIN                         30000
#define ID_SKIN_END                     32770
#define ID_EDIT_SKIN                    32771
#define ID_CONFIG                       32772
#define ID_POPUP_SELECTMONTH_JANUARY    32774
#define ID_POPUP_SELECTMONTH_FEBRUARY   32775
#define ID_REFRESH                      32776
#define ID_POPUP_SELECTMONTH_MARCH      32777
#define ID_QUIT                         32778
#define ID_POPUP_SELECTMONTH_APRIL      32779
#define ID_POPUP_SELECTMONTH_MAY        32780
#define ID_POPUP_SELECTMONTH_JUNE       32781
#define ID_POPUP_SELECTMONTH_JULY       32782
#define ID_POPUP_SELECTMONTH_AUGUST     32783
#define ID_POPUP_SELECTMONTH_SEPTEMBER  32784
#define ID_POPUP_SELECTMONTH_OCTOBER    32785
#define ID_POPUP_SELECTMONTH_NOVEMBER   32786
#define ID_POPUP_SELECTMONTH_DECEMBER   32787
#define ID_POPUP_SELECTMONTH_NEXTMONTH  32788
#define ID_POPUP_SELECTMONTH_PREVMONTH  32789
#define ID_SETEVENT                     32790
#define ID_POPUP_SELECTMONTH_CURRENTMONTH 32791
#define ID_ABOUT                        32793

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1023
#define _APS_NEXT_COMMAND_VALUE         32795
#define _APS_NEXT_CONTROL_VALUE         1193
#define _APS_NEXT_SYMED_VALUE           1000
#endif
#endif
